### ISSUE TITLE
Apache Superset

### ISSUE THREAD

**Issue by CourbeB** [saagie/technologies-community#1]
- [x] integrate superset 
- [x] documentation
- [x] add the main database Drivers https://superset.apache.org/docs/databases/installing-database-drivers
- [x] generate default admin user
- [x] configure gunicorn to run in production mode https://apache-superset.readthedocs.io/en/latest/installation.html#a-proper-wsgi-http-server
- [x] mount data and config directories

**Comment by tquiviger** [comment]
S'inspirer de https://hub.docker.com/r/amancevice/superset/
