### ISSUE TITLE
Saagie Monitoring Tool - Bugs in dashboards

### ISSUE THREAD

**Issue by tquiviger** [saagie/technologies-community#130]
In Jobs and Pipelines dashboards : 
- Longest Jobs viz is taking too long to show when many jobs are stored in PG 
- the Gradient Gauge is not showing progress between 0 to 100%
- Failure Ratio should be replaced by Success Ratio and SQL query should be optimized (too slow currently)

**Comment by saagie-service** [comment]
Trello card: [[#130] Saagie Monitoring Tool - Bugs in dashboards](https://trello.com/c/hwqqMMkt)
