### ISSUE TITLE
Increase infos tooltip dashboard "Jobs Failed / Killed Timeline"

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies-community#149]
It is difficult to know on dashboard Jobs Failed / Killed Timeline from Saagie Monitoring Tool witch job is failed or killed.

If it is possible it could be a good thing to add a legend with FAILED and KILLED. Otherwise add the information in tooltip.

**Comment by saagie-service** [comment]
Trello card: [[#149] Increase infos tooltip dashboard "Jobs Failed / Killed Timeline"](https://trello.com/c/WY56qnuQ)

**Comment by NicolasCD** [comment]
Merged
