### ISSUE TITLE
Saagie Monitoring Tool - General / Jobs and Pipelines - panels links 

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies-community#151]
When you select a time filter in dashboard _General / Jobs and Pipelines_ from Saagie Monitoring Tool, panels _Longest jobs (average duration)_ and _Success Ratio_ don't move.

A solution is to change queries of these two panels by adding **$__timeFilter(instance_start_time)** in WHERE clause.

**Comment by saagie-service** [comment]
Trello card: [[#151] Saagie Monitoring Tool - General / Jobs and Pipelines - panels links ](https://trello.com/c/QhcBFS2h)
