### ISSUE TITLE
Add project filter SMT "Jobs Failed Timeline"

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies-community#155]
Add a filter on projects in SMT "Jobs Failed Timeline" dashboard.
Add the possibility to select all projects

**Comment by saagie-service** [comment]
Trello card: [[#155] Add project filter SMT "Jobs Failed Timeline"](https://trello.com/c/mznbptJW)

**Comment by NicolasCD** [comment]
Closed with https://github.com/saagie/technologies-community/pull/156
