### ISSUE TITLE
Deprecation date format KO

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies-community#183]
The deprecation date for Saagie Monitoring Tool is not correct.
When you add the catalog in version 0.76.0 there is the error : 

**Cannot deserialize value of type `java.time.Instant` from String "2023-06-01 00:00:00": Failed to deserialize java.time.Instant: (java.time.format.DateTimeParseException) Text '2023-06-01 00:00:00' could not be parsed at index 10 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.saagie.technologymanager.infra.adapter.secondary.synchronization.model.v1.V1Technology$AppV1Technology["contexts"]->java.util.ArrayList[0]->io.saagie.technologymanager.infra.adapter.secondary.synchronization.model.v1.AppCatalogV1Context["deprecationDate"])**

**Comment by saagie-service** [comment]
Trello card: [[#183] Deprecation ate format KO](https://trello.com/c/FmwMTJKN)
