### ISSUE TITLE
Add PGAdmin4 in SUM and external postgresql

### ISSUE THREAD

**Issue by NicolasCD** [saagie/technologies-community#185]
The Postgresql data base in SUM is not accessible by external app. The PGadmin4 in the SUM allow this access.

It could be better to have the possibility to externalize the database. It could be done with environment variables.

**Comment by saagie-service** [comment]
Trello card: [[#185] Add PGAdmin4 in SUM and external postgresql](https://trello.com/c/qyNydTd7)
