### ISSUE TITLE
Remove the Saagie Usage Monitoring part from the saagie repository table technologies-community

### ISSUE THREAD

**Issue by annelhomme** [saagie/technologies-community#194]
![image](https://user-images.githubusercontent.com/78484821/226576142-5e9f9803-6eaa-4c82-9109-4d8334ab299b.png)

**Comment by saagie-service** [comment]
Trello card: [[#194] Remove the Saagie Usage Monitoring part from the saagie repository table technologies-community](https://trello.com/c/a96q2ApE)
