### ISSUE TITLE
Error in yaml of app Saagie Huggingface ModelServer

### ISSUE THREAD

**Issue by leshanshui-saagie** [saagie/technologies-community#213]
**Describe the bug**
docker version in .yaml of Saagie HuggingFace Model Server is in 'float' type not 'string' type
issue occured in app/saagie-hf-modelserver-textclf/metadata.yaml

> this float value is ambiguous : /{"contexts"}[0]{"dockerInfo"}{"version"} at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.saagie.technologymanager.infra.adapter.secondary.synchronization.model.v2.V2Technology$AppV2Technology["contexts"]->java.util.ArrayList[0]->io.saagie.technologymanager.infra.adapter.secondary.synchronization.model.v2.AppCatalogV2Context["dockerInfo"]->io.saagie.technologymanager.infra.adapter.secondary.synchronization.model.v2.V2DockerInfo["version"])

**Expected behavior**
The application image works

**Comment by saagie-service** [comment]
Trello card: [[#213] Error in yaml of app Saagie Huggingface ModelServer](https://trello.com/c/b68GHuor)
