### ISSUE TITLE
Custom icon doesn't manage correctly

### ISSUE THREAD

**Issue by guillaumeprevost76** [saagie/technologies-community#221]
**Describe the bug**
I created a technology based on a custom icon. It works correctly when I created manually the technology.zip
But on new version, when the package is created automatically by the CI/CD, the icon was not present and I got an error.

**Expected behavior**
Modify the CI/CD process to include the icon files inside the package generated.

**Comment by saagie-service** [comment]
Trello card: [[#221] Custom icon doesn't manage correctly](https://trello.com/c/Q04kUcQv)
